use [PMSNexus_Appraisal]
/*
truncate table [dbo].[AppraisalMaster]
truncate table [dbo].[EmployeeAppraisalConversation]
truncate table [dbo].[EmployeeAppraisalMaster]
truncate table [dbo].[EmployeeGroupRating]
truncate table [dbo].[EmployeeGroupSelection]
truncate table [dbo].[EmployeeKeyResultAttachments]
truncate table [dbo].[EmployeeKeyResultConversation]
truncate table [dbo].[EmployeeKeyResultRating]
truncate table [dbo].[EmployeeObjectiveRating]
truncate table [dbo].[EntityMaster]
truncate table [dbo].[KeyResultMaster]
truncate table [dbo].[ObjectiveMaster]
truncate table [dbo].[VersionBenchMarks]
truncate table [dbo].[VersionDepartmentRoleMapping]
truncate table [dbo].[VersionDepartmentRoleObjective]
truncate table [dbo].[VersionDepartments]
truncate table [dbo].[VersionKeyResults]
truncate table [dbo].[VersionKeyResultsGroup]
truncate table [dbo].[VersionKeyResultsGroupDetails]
truncate table [dbo].[VersionMaster]
truncate table [dbo].[VersionObjective]

*/

select * from [dbo].[AppraisalMaster]
select * from [dbo].[EmployeeAppraisalConversation]
select * from [dbo].[EmployeeAppraisalMaster]
select * from  [dbo].[EmployeeGroupRating]
select * from  [dbo].[EmployeeGroupSelection]
select * from  [dbo].[EmployeeKeyResultAttachments]
select * from  [dbo].[EmployeeKeyResultConversation]
select * from  [dbo].[EmployeeKeyResultRating]
select * from  [dbo].[EmployeeObjectiveRating]
select * from  [dbo].[EntityMaster]
select * from  [dbo].[KeyResultMaster]
select * from [dbo].[ObjectiveMaster]
select * from  [dbo].[VersionBenchMarks]
select * from  [dbo].[VersionDepartmentRoleMapping]
select * from  [dbo].[VersionDepartmentRoleObjective]
select * from  [dbo].[VersionDepartments]
select * from  [dbo].[VersionKeyResults]
select * from  [dbo].[VersionKeyResultsGroup]
select * from  [dbo].[VersionKeyResultsGroupDetails]
select * from  [dbo].[VersionMaster]
select * from  [dbo].[VersionObjective]