IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Status')
CREATE TABLE [dbo].[Status](
[StatusId] [int] IDENTITY(1,1) NOT NULL,
[StatusCode] [VARCHAR](100) NULL,
[StatusName] [VARCHAR](200) NULL,
[CreatedOn] [datetime] NULL,
[CreatedBy] [int] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [int] NULL
PRIMARY KEY CLUSTERED 
	(
		[StatusId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
GO