TRUNCATE TABLE [Roles]
GO

INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'UI/UX Designers', N'UIUX', N'UI/UX Designers', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Solution Consultant', N'SRSOLCONS', N'Sr. Solution Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Consultant', N'SRCONS', N'Sr. Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Pre-Sales Consultant', N'SRPRECONS', N'Sr. Pre-Sales Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Leader - CX', N'LDRCX', N'Leader - CX', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Trainee Consultant', N'TRAINCONS', N'Trainee Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Senior Systems/Network Engineer', N'SRSYSENGG', N'Senior Systems/Network Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Network/Systems Engineer', N'SYSENGG', N'Network/Systems Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'IT Support Engineer', N'ITSUPPENGG', N'Support Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'IT Manager', N'ITMGR', N'IT Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'SDR', N'SDR', N'SDR', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Associate Manager', N'ASSMGR', N'Associate Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager Sales (US)', N'MGR', N'Manager Sales (US)', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Leader - Sales', N'SALLEAD', N'Leader - Sales', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'SDR (India)', N'SDRIND', N'SDR (India)', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager Sales (India)', N'MGRSAL', N'Manager Sales (India)', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'VP Sales', N'VPSAL', N'VP Sales', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'RMG', N'RMG', N'RMG', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'HR VP', N'VPHR', N'HR VP', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Senior Executive HR', N'SREXECHR', N'Senior Executive HR', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'HR Manager', N'HRMGR', N'HR Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Trainee SAP', N'SAPTRAIN', N'Trainee SAP', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Associate Consultant', N'ASSOCONS', N'Associate Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Consultant', N'CONS', N'Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Consultant', N'LEADCONS', N'Lead Consultant', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Delivery Head - SAP', N'SAPDELHEAD', N'Delivery Head - SAP', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Network Engineer', N'NWENGG', N'Network Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Asst Manager - IT', N'ITASSTMGR', N'Asst Manager - IT', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Deputy Manager', N'DEPMGR', N'Deputy Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager', N'MGR', N'Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Delivery Head - IT', N'ITDELHEAD', N'Delivery Head - IT', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Dev Engineer', N'DEVENGG', N'Dev Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Technical Project Manager', N'TPM', N'Technical Project Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manual QA Engineer', N'QAENGGMAN', N'Manual QA Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Engineer', N'ENGGLD', N'Lead Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Manual QA Engineer', N'QAENGGMANL', N'Lead Manual QA Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Automation QA Engineer', N'QAENGGAUT', N'Automation QA Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Support Engineer', N'SUPPENGG', N'Support Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Support Engineer', N'SUPPENGGLD', N'Lead Support Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Automation QA Engineer', N'QAENGGAUTL', N'Lead Automation QA Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'DevOps Engineer', N'DEVOPS', N'DevOps Engineer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Scrum Master', N'SCM', N'Scrum Master', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Engineering Leader', N'ENGGLEAD', N'Engineering Leader', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive Accounting', N'EXEACC', N'Executive Accounting', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive Reporting', N'EXEREP', N'Executive Reporting', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Finance Manager', N'FINMGR', N'Finance Manager', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Finance Head', N'FINHD', N'Finance Head', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'US Recruiter', N'USREC', N'US Recruiter', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Leader - Recruitment', N'USLDREC', N'Leader - Recruitment', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive - Data & Campaigns', N'DNCEXE', N'Executive - Data & Campaigns', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Executive - Data & Campaigns', N'DNCSREXE', N'Sr. Executive - Data & Campaigns', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager - Data & Campaigns', N'DNCMGR', N'Manager - Data & Campaigns', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive - Social Media & Website', N'SMNWBEXE', N'Executive - Social Media & Website', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Executive - Social Media & Website', N'SMNWBSREXE', N'Sr. Executive - Social Media & Website', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager - Social Media & Website', N'SMNWBMGR', N'Manager - Social Media & Website', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive - Content', N'CONTEXE', N'Executive - Content', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Executive - Content', N'CONTSREXE', N'Sr. Executive - Content', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager - Content', N'CONTMGR', N'Manager - Content', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Executive - Creatives', N'CREAEXE', N'Executive - Creatives', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Sr. Executive - Creatives', N'CREASREXE', N'Sr. Executive - Creatives', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Manager - Creatives', N'CREAMGR', N'Manager - Creatives', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Leader - Marketing', N'LDRMKTNG', N'Leader - Marketing', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Lead Recruiter', N'LDRRCT', N'Lead Recruiter', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Senior Recruiter', N'SLDRRCT', N'Senior Recruiter', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Recruiter', N'RCT', N'Recruiter', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Admin', N'ADMN', N'Administrator', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Cheif Operations Officer', N'COO', N'Cheif Operations Officer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'Cheif Executive Officer', N'CEO', N'Cheif Executive Officer', 1, GETDATE())
INSERT [dbo].[Roles] ([RoleName], [RoleShortName], [RoleDescription], [CreatedBy], [CreatedOn]) VALUES (N'SFL Head', N'SFLH', N'SFL Head', 1, GETDATE())
GO