USE [PMSNexus_Employees]
TRUNCATE TABLE EmployeeCountry
GO
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('India')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('United States')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Afghanistan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Aland Islands (Finland)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Albania')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Algeria')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('American Samoa (USA)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Andorra')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Angola')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Anguilla (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Antigua and Barbuda')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Argentina')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Armenia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Aruba (Netherlands)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Australia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Austria')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Azerbaijan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bahamas')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bahrain')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bangladesh')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Barbados')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Belarus')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Belgium')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Belize')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Benin')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bermuda (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bhutan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bolivia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bosnia and Herzegovina')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Botswana')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Brazil')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('British Virgin Islands (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Brunei')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Bulgaria')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Burkina Faso')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Burma')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Burundi')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cambodia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cameroon')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Canada')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cape Verde')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Caribbean Netherlands (Netherlands)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cayman Islands (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Central African Republic')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Chad')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Chile')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('China')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Christmas Island (Australia)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cocos (Keeling) Islands (Australia)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Colombia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Comoros')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cook Islands (NZ)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Costa Rica')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Croatia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cuba')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Curacao (Netherlands)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Cyprus')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Czech Republic')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Democratic Republic of the Congo')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Denmark')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Djibouti')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Dominica')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Dominican Republic')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ecuador')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Egypt')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('El Salvador')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Equatorial Guinea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Eritrea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Estonia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ethiopia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Falkland Islands (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Faroe Islands (Denmark)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Federated States of Micronesia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Fiji')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Finland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('France')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('French Guiana (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('French Polynesia (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Gabon')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Gambia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Georgia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Germany')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ghana')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Gibraltar (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Greece')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Greenland (Denmark)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Grenada')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guadeloupe (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guam (USA)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guatemala')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guernsey (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guinea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guinea-Bissau')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Guyana')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Haiti')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Honduras')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Hong Kong (China)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Hungary')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Iceland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Indonesia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Iran')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Iraq')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ireland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Isle of Man (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Israel')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Italy')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ivory Coast')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Jamaica')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Japan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Jersey (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Jordan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kazakhstan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kenya')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kiribati')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kosovo')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kuwait')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Kyrgyzstan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Laos')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Latvia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Lebanon')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Lesotho')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Liberia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Libya')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Liechtenstein')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Lithuania')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Luxembourg')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Macau (China)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Macedonia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Madagascar')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Malawi')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Malaysia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Maldives')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mali')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Malta')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Marshall Islands')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Martinique (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mauritania')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mauritius')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mayotte (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mexico')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Moldov')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Monaco')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mongolia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Montenegro')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Montserrat (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Morocco')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Mozambique')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Namibia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Nauru')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Nepal')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Netherlands')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('New Caledonia (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('New Zealand')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Nicaragua')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Niger')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Nigeria')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Niue (NZ)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Norfolk Island (Australia)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('North Korea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Northern Mariana Islands (USA)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Norway')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Oman')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Pakistan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Palau')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Palestine')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Panama')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Papua New Guinea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Paraguay')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Peru')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Philippines')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Pitcairn Islands (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Poland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Portugal')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Puerto Rico')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Qatar')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Republic of the Congo')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Reunion (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Romania')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Russia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Rwanda')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Barthelemy (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Helena, Ascension and Tristan da Cunha (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Kitts and Nevis')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Lucia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Martin (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Pierre and Miquelon (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saint Vincent and the Grenadines')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Samoa')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('San Marino')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sao Tom and Principe')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Saudi Arabia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Senegal')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Serbia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Seychelles')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sierra Leone')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Singapore')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sint Maarten (Netherlands)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Slovakia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Slovenia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Solomon Islands')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Somalia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('South Africa')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('South Korea')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('South Sudan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Spain')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sri Lanka')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sudan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Suriname')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Svalbard and Jan Mayen (Norway)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Swaziland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Sweden')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Switzerland')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Syria')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Taiwan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tajikistan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tanzania')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Thailand')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Timor-Leste')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Togo')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tokelau (NZ)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tonga')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Trinidad and Tobago')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tunisia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Turkey')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Turkmenistan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Turks and Caicos Islands (UK)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Tuvalu')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Uganda')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Ukraine')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('United Arab Emirates')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('United Kingdom')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('United States Virgin Islands (USA)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Uruguay')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Uzbekistan')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Vanuatu')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Vatican City')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Venezuela')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Vietnam')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Wallis and Futuna (France)')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Western Sahara')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Yemen')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Zambia')
INSERT INTO EmployeeCountry ([CountryName]) VALUES ('Zimbabwe')
GO

TRUNCATE TABLE [EmployeeState]
GO
DECLARE @CountryId INT
SELECT @CountryId = [CountryId] FROM EmployeeCountry where [CountryName] = 'India'
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Andhra Pradesh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Arunachal Pradesh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Assam')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Bihar')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Chhattisgarh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Goa')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Gujarat')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Haryana')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Himachal Pradesh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Jammu and Kashmir')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Jharkhand')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Karnataka')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Kerala')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Madhya Pradesh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Maharashtra')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Manipur')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Meghalaya')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Mizoram')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Nagaland')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Orissa')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Punjab')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Rajasthan')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Sikkim')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Tamil Nadu')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Telangana')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Tripura')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Uttar Pradesh')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Uttaranchal')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'West Bengal')
GO
DECLARE @CountryId INT
SELECT @CountryId = [CountryId] FROM EmployeeCountry where [CountryName] = 'United States'
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Alabama')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Alaska')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Arizona')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Arkansas')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'California')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Colorado')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Connecticut')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Delaware')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Florida')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Georgia')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Hawaii')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Idaho')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Illinois')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Indiana')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Iowa')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Kansas')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Kentucky[upper-alpha 3]')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Louisiana')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Maine')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Maryland')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Massachusetts[upper-alpha 3]')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Michigan')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Minnesota')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Mississippi')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Missouri')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Montana')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Nebraska')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Nevada')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'New Hampshire')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'New Jersey')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'New Mexico')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'New York')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'North Carolina')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'North Dakota')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Ohio')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Oklahoma')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Oregon')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Pennsylvania[upper-alpha 3]')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Rhode Island[upper-alpha 4]')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'South Carolina')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'South Dakota')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Tennessee')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Texas')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Utah')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Vermont')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Virginia[upper-alpha 3]')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Washington')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'West Virginia')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Wisconsin')
INSERT INTO [EmployeeState] ([CountryId], [StateName]) VALUES (@CountryId, 'Wyoming')
GO