USE [PMSNexus_Leaves]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Holiday' AND COLUMN_NAME = 'HolidayDate')
BEGIN
	ALTER TABLE [dbo].[Holiday] ADD HolidayDate Date NULL
END
GO