USE [PMSNexus_Attendance]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ShiftDetails' AND COLUMN_NAME = 'IsActive')
BEGIN
	ALTER TABLE [dbo].[ShiftDetails] ADD IsActive Bit NULL
END
GO