USE [PMSNexus_Employees]
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'EmployeeGrade')
ALTER TABLE [Employees] ADD [EmployeeGrade] [int] NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'Extension')
ALTER TABLE [Employees] ADD [Extension] [varchar](250) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'TVSNextExperience')
ALTER TABLE [Employees] ADD [TVSNextExperience] [decimal](18,2) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'OfficialMobileNumber')
ALTER TABLE [Employees] ADD [OfficialMobileNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'Qualification')
ALTER TABLE [Employees] ADD [Qualification] [varchar](250) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'PersonalMobileNumber')
ALTER TABLE [Employees] ADD [PersonalMobileNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'OtherEmail')
ALTER TABLE [Employees] ADD [OtherEmail] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'BirthDate')
ALTER TABLE [Employees] ADD [BirthDate]  Date NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'WeddingAnniversary')
ALTER TABLE [Employees] ADD [WeddingAnniversary] Date NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'Maritalstatus')
ALTER TABLE [Employees] ADD [Maritalstatus] [varchar](10) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'BloodGroup')
ALTER TABLE [Employees] ADD [BloodGroup] [varchar](10) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'PermanentAddress')
ALTER TABLE [Employees] ADD [PermanentAddress] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'FathersName')
ALTER TABLE [Employees] ADD [FathersName] [varchar](250) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'EmergencyMobileNumber')
ALTER TABLE [Employees] ADD [EmergencyMobileNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'Nationality')
ALTER TABLE [Employees] ADD [Nationality] [varchar](250) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'CommunicationAddress')
ALTER TABLE [Employees] ADD [CommunicationAddress] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'PANNumber')
ALTER TABLE [Employees] ADD [PANNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'UANNumber')
ALTER TABLE [Employees] ADD [UANNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'DrivingLicense')
ALTER TABLE [Employees] ADD [DrivingLicense] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees' AND COLUMN_NAME = 'AadhaarCardNumber')
ALTER TABLE [Employees] ADD [AadhaarCardNumber] [varchar](2000) NULL
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employees'  AND COLUMN_NAME = 'PassportNumber')
ALTER TABLE [Employees] ADD [PassportNumber] [varchar](2000) NULL
GO