USE [PMSNexus_Employees]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Features' AND  COLUMN_NAME = 'NavigationURL')
BEGIN
	ALTER TABLE [dbo].[Features] ADD NavigationURL VARCHAR(1000)
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Modules' AND  COLUMN_NAME = 'ModuleIcon')
BEGIN
	ALTER TABLE [dbo].[Modules] ADD ModuleIcon VARCHAR(250)
END
GO