USE [PMSNexus_Appraisal]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='VersionKeyResults' AND COLUMN_NAME = 'IS_DOCUMENT_MANDATORY')
BEGIN
	ALTER TABLE [dbo].[VersionKeyResults] ADD IS_DOCUMENT_MANDATORY bit NULL
END

GO

