USE [PMSNexus_Appraisal]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='VersionKeyResults' AND COLUMN_NAME = 'BENCHMARK_UITYPE')
BEGIN
	ALTER TABLE [dbo].[VersionKeyResults] ADD BENCHMARK_UITYPE int NULL
END

GO

IF NOT EXISTS (SELECT 1 FROM AppConstantType where APP_CONSTANT_TYPE_DESC='UI Type')
BEGIN
	INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('UI Type',1,GETDATE(),1,GETDATE())
END
Go

declare @AppConstantTypeId int
select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='UI Type';
IF NOT EXISTS (SELECT 1 FROM AppConstants where APP_CONSTANT_TYPE_ID=@AppConstantTypeId)
BEGIN
	INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Slider',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'LOV',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Counter',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Smiley',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Timer',1,GETDATE(),1,GETDATE())
END


