USE [PMSNexus_Appraisal]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AppraisalMaster' AND  COLUMN_NAME = 'DURATION_ID')
BEGIN
	ALTER TABLE [dbo].[AppraisalMaster] ADD DURATION_ID int NULL
END
GO