USE [PMSNexus_Leaves]
GO
USE [PMSNexus_Leaves]
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'WeekendCountAfterDays')
BEGIN
	ALTER TABLE LeaveRestrictions DROP COLUMN WeekendCountAfterDays
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'HolidayCountAfterDays')
BEGIN
	ALTER TABLE LeaveRestrictions DROP COLUMN HolidayCountAfterDays
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'DurationsAllowedId')
BEGIN
	ALTER TABLE LeaveRestrictions DROP COLUMN DurationsAllowedId
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'BalanceDisplayedId')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN BalanceDisplayedId decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'DaysInAdvance')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN DaysInAdvance decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'AllowRequestNextDays')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN AllowRequestNextDays decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'DatesAppliedAdvance')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN DatesAppliedAdvance decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'MinimumLeavePerApplication')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN MinimumLeavePerApplication decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'MinimumGapTwoApplication')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN MinimumGapTwoApplication decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'MinimumConsecutiveDays')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN MinimumConsecutiveDays decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'MinimumNoOfApplicationsPeriod')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN MinimumNoOfApplicationsPeriod decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'EnableFileUpload')
BEGIN
	ALTER TABLE LeaveRestrictions ALTER COLUMN EnableFileUpload decimal
END
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveRestrictions' AND COLUMN_NAME = 'WeeksId')
BEGIN
	EXEC sp_RENAME 'LeaveRestrictions.WeeksId','AllowRequestPeriodId','COLUMN'
END
GO



