USE [PMSNexus_Projects]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProjectDetails' AND  COLUMN_NAME = 'BUAccountableForProject')
BEGIN
	ALTER TABLE ProjectDetails ADD BUAccountableForProject INT NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProjectDetails' AND  COLUMN_NAME = 'Logo')
BEGIN
	ALTER TABLE ProjectDetails ADD Logo VARCHAR(MAX) NULL
END
GO