USE [PMSNexus_Appraisal]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='EmployeeAppraisalMaster' AND COLUMN_NAME = 'IsBUHeadRevert')
BEGIN
	ALTER TABLE [dbo].[EmployeeAppraisalMaster] ADD IsBUHeadRevert bit NULL DEFAULT (0) WITH VALUES 
	
END
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='EmployeeAppraisalMaster' AND COLUMN_NAME = 'IsRevertRating')
BEGIN
	ALTER TABLE [dbo].[EmployeeAppraisalMaster] ADD IsRevertRating bit NULL DEFAULT (0) WITH VALUES 
	
END
GO