USE [PMSNexus_Leaves]
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveTypes' AND COLUMN_NAME = 'LeaveAccruedType')
BEGIN
	ALTER TABLE LeaveTypes ALTER COLUMN LeaveAccruedType int
END
GO