USE [PMSNexus_Accounts]
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AccountDetails' AND  COLUMN_NAME = 'Logo')
BEGIN
	ALTER TABLE AccountDetails ADD Logo VARCHAR(MAX) NULL
END
GO