USE [PMSNexus_Leaves]
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'MaxLimitDays')
BEGIN
ALTER TABLE LeaveEntitlement DROP COLUMN MaxLimitDays
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'AllowEncashmentCarryForward')
BEGIN
ALTER TABLE LeaveEntitlement DROP COLUMN AllowEncashmentCarryForward
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'NoOfDays')
BEGIN
ALTER TABLE LeaveEntitlement DROP COLUMN NoOfDays
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'LeaveMaxLimitActionId')
BEGIN
ALTER TABLE LeaveEntitlement DROP COLUMN LeaveMaxLimitActionId
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'CarryForwardId')
BEGIN
ALTER TABLE LeaveEntitlement ADD CarryForwardId int NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'MaximumCarryForwardDays')
BEGIN
ALTER TABLE LeaveEntitlement ADD MaximumCarryForwardDays decimal NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'ReimbursementId')
BEGIN
ALTER TABLE LeaveEntitlement ADD ReimbursementId int NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'MaximumReimbursementDays')
BEGIN
ALTER TABLE LeaveEntitlement ADD MaximumReimbursementDays decimal NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'ResetYear')
BEGIN
ALTER TABLE LeaveEntitlement ADD ResetYear int NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'ResetMonth')
BEGIN
ALTER TABLE LeaveEntitlement ADD ResetMonth int NULL
END
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'ResetDay')
BEGIN
ALTER TABLE LeaveEntitlement ADD ResetDay varchar(100) NULL
END
GO


