USE [PMSNexus_Leaves]
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProRateMonthDetails' AND COLUMN_NAME = 'Fromday')
BEGIN
	ALTER TABLE ProRateMonthDetails ALTER COLUMN Fromday varchar(100)
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProRateMonthDetails' AND COLUMN_NAME = 'Today')
BEGIN
	ALTER TABLE ProRateMonthDetails ALTER COLUMN Today varchar(100)
END
GO