USE [PMSNexus_Leaves]
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'MaxLeaveAvailedDays')
BEGIN
	ALTER TABLE LeaveEntitlement ALTER COLUMN MaxLeaveAvailedDays decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'MaxLimitDays')
BEGIN
	ALTER TABLE LeaveEntitlement ALTER COLUMN MaxLimitDays decimal
END
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveEntitlement' AND COLUMN_NAME = 'NoOfDays')
BEGIN
	ALTER TABLE LeaveEntitlement ALTER COLUMN NoOfDays decimal
END
GO





