USE [PMSNexus_Leaves]
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveTypes' AND COLUMN_NAME = 'LeaveAccruedNoOfDays')
BEGIN
	ALTER TABLE LeaveTypes ALTER COLUMN LeaveAccruedNoOfDays decimal(18,2)
END
GO