USE [PMSNexus_Leaves]

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='LeaveTypes' AND COLUMN_NAME = 'IsActive' )
	BEGIN
	ALTER TABLE LeaveTypes ADD [IsActive] [bit] NULL
END

GO