USE [PMSNexus_Attendance]

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AttendanceDetail' AND COLUMN_NAME = 'RejectReason' )
	BEGIN
	ALTER TABLE AttendanceDetail ADD RejectReason varchar(500) NULL
END
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AttendanceDetail' AND COLUMN_NAME = 'Status' )
	BEGIN
	ALTER TABLE AttendanceDetail ALTER COLUMN Status varchar(500) NULL
END
GO