USE [PMSNexus_Attendance]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='AttendanceDetail' AND COLUMN_NAME = 'ManagerId')
BEGIN
	ALTER TABLE [dbo].[AttendanceDetail] ADD ManagerId int NULL
END
GO