USE [PMSNexus_Leaves]
GO
IF  EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ProRateMonthDetails' AND COLUMN_NAME = 'Count')
BEGIN
	ALTER TABLE ProRateMonthDetails ALTER COLUMN [Count] decimal(18,2)
END
GO