USE [PMSNexus_Attendance]
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ShiftDetails' AND COLUMN_NAME = 'IsFlexyShift')
BEGIN
	ALTER TABLE [dbo].[ShiftDetails] ADD IsFlexyShift Bit NULL
END
GO