USE [PMSNexus_Accounts]
GO

TRUNCATE TABLE AccountType
GO
INSERT INTO AccountType ([AccountTypeName], CreatedOn, CreatedBy) VALUES ('Healthcare', GETDATE(), 1)
INSERT INTO AccountType ([AccountTypeName], CreatedOn, CreatedBy) VALUES ('BFSI', GETDATE(), 1)
INSERT INTO AccountType ([AccountTypeName], CreatedOn, CreatedBy) VALUES ('Textile', GETDATE(), 1)
INSERT INTO AccountType ([AccountTypeName], CreatedOn, CreatedBy) VALUES ('Logistics', GETDATE(), 1)
GO

TRUNCATE TABLE BillingCycle
GO

INSERT INTO BillingCycle(BillingCycleDescription, CreatedOn, CreatedBy) VALUES('Monthly', GETDATE(), 1)
INSERT INTO BillingCycle(BillingCycleDescription, CreatedOn, CreatedBy) VALUES('Quarterly', GETDATE(), 1)
INSERT INTO BillingCycle(BillingCycleDescription, CreatedOn, CreatedBy) VALUES('Halfyearly', GETDATE(), 1)
INSERT INTO BillingCycle(BillingCycleDescription, CreatedOn, CreatedBy) VALUES('Annual', GETDATE(), 1)
GO
 
TRUNCATE TABLE Country
GO
INSERT INTO Country ([CountryName]) VALUES ('India')
INSERT INTO Country ([CountryName]) VALUES ('United States')
INSERT INTO Country ([CountryName]) VALUES ('Afghanistan')
INSERT INTO Country ([CountryName]) VALUES ('Aland Islands (Finland)')
INSERT INTO Country ([CountryName]) VALUES ('Albania')
INSERT INTO Country ([CountryName]) VALUES ('Algeria')
INSERT INTO Country ([CountryName]) VALUES ('American Samoa (USA)')
INSERT INTO Country ([CountryName]) VALUES ('Andorra')
INSERT INTO Country ([CountryName]) VALUES ('Angola')
INSERT INTO Country ([CountryName]) VALUES ('Anguilla (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Antigua and Barbuda')
INSERT INTO Country ([CountryName]) VALUES ('Argentina')
INSERT INTO Country ([CountryName]) VALUES ('Armenia')
INSERT INTO Country ([CountryName]) VALUES ('Aruba (Netherlands)')
INSERT INTO Country ([CountryName]) VALUES ('Australia')
INSERT INTO Country ([CountryName]) VALUES ('Austria')
INSERT INTO Country ([CountryName]) VALUES ('Azerbaijan')
INSERT INTO Country ([CountryName]) VALUES ('Bahamas')
INSERT INTO Country ([CountryName]) VALUES ('Bahrain')
INSERT INTO Country ([CountryName]) VALUES ('Bangladesh')
INSERT INTO Country ([CountryName]) VALUES ('Barbados')
INSERT INTO Country ([CountryName]) VALUES ('Belarus')
INSERT INTO Country ([CountryName]) VALUES ('Belgium')
INSERT INTO Country ([CountryName]) VALUES ('Belize')
INSERT INTO Country ([CountryName]) VALUES ('Benin')
INSERT INTO Country ([CountryName]) VALUES ('Bermuda (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Bhutan')
INSERT INTO Country ([CountryName]) VALUES ('Bolivia')
INSERT INTO Country ([CountryName]) VALUES ('Bosnia and Herzegovina')
INSERT INTO Country ([CountryName]) VALUES ('Botswana')
INSERT INTO Country ([CountryName]) VALUES ('Brazil')
INSERT INTO Country ([CountryName]) VALUES ('British Virgin Islands (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Brunei')
INSERT INTO Country ([CountryName]) VALUES ('Bulgaria')
INSERT INTO Country ([CountryName]) VALUES ('Burkina Faso')
INSERT INTO Country ([CountryName]) VALUES ('Burma')
INSERT INTO Country ([CountryName]) VALUES ('Burundi')
INSERT INTO Country ([CountryName]) VALUES ('Cambodia')
INSERT INTO Country ([CountryName]) VALUES ('Cameroon')
INSERT INTO Country ([CountryName]) VALUES ('Canada')
INSERT INTO Country ([CountryName]) VALUES ('Cape Verde')
INSERT INTO Country ([CountryName]) VALUES ('Caribbean Netherlands (Netherlands)')
INSERT INTO Country ([CountryName]) VALUES ('Cayman Islands (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Central African Republic')
INSERT INTO Country ([CountryName]) VALUES ('Chad')
INSERT INTO Country ([CountryName]) VALUES ('Chile')
INSERT INTO Country ([CountryName]) VALUES ('China')
INSERT INTO Country ([CountryName]) VALUES ('Christmas Island (Australia)')
INSERT INTO Country ([CountryName]) VALUES ('Cocos (Keeling) Islands (Australia)')
INSERT INTO Country ([CountryName]) VALUES ('Colombia')
INSERT INTO Country ([CountryName]) VALUES ('Comoros')
INSERT INTO Country ([CountryName]) VALUES ('Cook Islands (NZ)')
INSERT INTO Country ([CountryName]) VALUES ('Costa Rica')
INSERT INTO Country ([CountryName]) VALUES ('Croatia')
INSERT INTO Country ([CountryName]) VALUES ('Cuba')
INSERT INTO Country ([CountryName]) VALUES ('Curacao (Netherlands)')
INSERT INTO Country ([CountryName]) VALUES ('Cyprus')
INSERT INTO Country ([CountryName]) VALUES ('Czech Republic')
INSERT INTO Country ([CountryName]) VALUES ('Democratic Republic of the Congo')
INSERT INTO Country ([CountryName]) VALUES ('Denmark')
INSERT INTO Country ([CountryName]) VALUES ('Djibouti')
INSERT INTO Country ([CountryName]) VALUES ('Dominica')
INSERT INTO Country ([CountryName]) VALUES ('Dominican Republic')
INSERT INTO Country ([CountryName]) VALUES ('Ecuador')
INSERT INTO Country ([CountryName]) VALUES ('Egypt')
INSERT INTO Country ([CountryName]) VALUES ('El Salvador')
INSERT INTO Country ([CountryName]) VALUES ('Equatorial Guinea')
INSERT INTO Country ([CountryName]) VALUES ('Eritrea')
INSERT INTO Country ([CountryName]) VALUES ('Estonia')
INSERT INTO Country ([CountryName]) VALUES ('Ethiopia')
INSERT INTO Country ([CountryName]) VALUES ('Falkland Islands (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Faroe Islands (Denmark)')
INSERT INTO Country ([CountryName]) VALUES ('Federated States of Micronesia')
INSERT INTO Country ([CountryName]) VALUES ('Fiji')
INSERT INTO Country ([CountryName]) VALUES ('Finland')
INSERT INTO Country ([CountryName]) VALUES ('France')
INSERT INTO Country ([CountryName]) VALUES ('French Guiana (France)')
INSERT INTO Country ([CountryName]) VALUES ('French Polynesia (France)')
INSERT INTO Country ([CountryName]) VALUES ('Gabon')
INSERT INTO Country ([CountryName]) VALUES ('Gambia')
INSERT INTO Country ([CountryName]) VALUES ('Georgia')
INSERT INTO Country ([CountryName]) VALUES ('Germany')
INSERT INTO Country ([CountryName]) VALUES ('Ghana')
INSERT INTO Country ([CountryName]) VALUES ('Gibraltar (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Greece')
INSERT INTO Country ([CountryName]) VALUES ('Greenland (Denmark)')
INSERT INTO Country ([CountryName]) VALUES ('Grenada')
INSERT INTO Country ([CountryName]) VALUES ('Guadeloupe (France)')
INSERT INTO Country ([CountryName]) VALUES ('Guam (USA)')
INSERT INTO Country ([CountryName]) VALUES ('Guatemala')
INSERT INTO Country ([CountryName]) VALUES ('Guernsey (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Guinea')
INSERT INTO Country ([CountryName]) VALUES ('Guinea-Bissau')
INSERT INTO Country ([CountryName]) VALUES ('Guyana')
INSERT INTO Country ([CountryName]) VALUES ('Haiti')
INSERT INTO Country ([CountryName]) VALUES ('Honduras')
INSERT INTO Country ([CountryName]) VALUES ('Hong Kong (China)')
INSERT INTO Country ([CountryName]) VALUES ('Hungary')
INSERT INTO Country ([CountryName]) VALUES ('Iceland')
INSERT INTO Country ([CountryName]) VALUES ('Indonesia')
INSERT INTO Country ([CountryName]) VALUES ('Iran')
INSERT INTO Country ([CountryName]) VALUES ('Iraq')
INSERT INTO Country ([CountryName]) VALUES ('Ireland')
INSERT INTO Country ([CountryName]) VALUES ('Isle of Man (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Israel')
INSERT INTO Country ([CountryName]) VALUES ('Italy')
INSERT INTO Country ([CountryName]) VALUES ('Ivory Coast')
INSERT INTO Country ([CountryName]) VALUES ('Jamaica')
INSERT INTO Country ([CountryName]) VALUES ('Japan')
INSERT INTO Country ([CountryName]) VALUES ('Jersey (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Jordan')
INSERT INTO Country ([CountryName]) VALUES ('Kazakhstan')
INSERT INTO Country ([CountryName]) VALUES ('Kenya')
INSERT INTO Country ([CountryName]) VALUES ('Kiribati')
INSERT INTO Country ([CountryName]) VALUES ('Kosovo')
INSERT INTO Country ([CountryName]) VALUES ('Kuwait')
INSERT INTO Country ([CountryName]) VALUES ('Kyrgyzstan')
INSERT INTO Country ([CountryName]) VALUES ('Laos')
INSERT INTO Country ([CountryName]) VALUES ('Latvia')
INSERT INTO Country ([CountryName]) VALUES ('Lebanon')
INSERT INTO Country ([CountryName]) VALUES ('Lesotho')
INSERT INTO Country ([CountryName]) VALUES ('Liberia')
INSERT INTO Country ([CountryName]) VALUES ('Libya')
INSERT INTO Country ([CountryName]) VALUES ('Liechtenstein')
INSERT INTO Country ([CountryName]) VALUES ('Lithuania')
INSERT INTO Country ([CountryName]) VALUES ('Luxembourg')
INSERT INTO Country ([CountryName]) VALUES ('Macau (China)')
INSERT INTO Country ([CountryName]) VALUES ('Macedonia')
INSERT INTO Country ([CountryName]) VALUES ('Madagascar')
INSERT INTO Country ([CountryName]) VALUES ('Malawi')
INSERT INTO Country ([CountryName]) VALUES ('Malaysia')
INSERT INTO Country ([CountryName]) VALUES ('Maldives')
INSERT INTO Country ([CountryName]) VALUES ('Mali')
INSERT INTO Country ([CountryName]) VALUES ('Malta')
INSERT INTO Country ([CountryName]) VALUES ('Marshall Islands')
INSERT INTO Country ([CountryName]) VALUES ('Martinique (France)')
INSERT INTO Country ([CountryName]) VALUES ('Mauritania')
INSERT INTO Country ([CountryName]) VALUES ('Mauritius')
INSERT INTO Country ([CountryName]) VALUES ('Mayotte (France)')
INSERT INTO Country ([CountryName]) VALUES ('Mexico')
INSERT INTO Country ([CountryName]) VALUES ('Moldov')
INSERT INTO Country ([CountryName]) VALUES ('Monaco')
INSERT INTO Country ([CountryName]) VALUES ('Mongolia')
INSERT INTO Country ([CountryName]) VALUES ('Montenegro')
INSERT INTO Country ([CountryName]) VALUES ('Montserrat (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Morocco')
INSERT INTO Country ([CountryName]) VALUES ('Mozambique')
INSERT INTO Country ([CountryName]) VALUES ('Namibia')
INSERT INTO Country ([CountryName]) VALUES ('Nauru')
INSERT INTO Country ([CountryName]) VALUES ('Nepal')
INSERT INTO Country ([CountryName]) VALUES ('Netherlands')
INSERT INTO Country ([CountryName]) VALUES ('New Caledonia (France)')
INSERT INTO Country ([CountryName]) VALUES ('New Zealand')
INSERT INTO Country ([CountryName]) VALUES ('Nicaragua')
INSERT INTO Country ([CountryName]) VALUES ('Niger')
INSERT INTO Country ([CountryName]) VALUES ('Nigeria')
INSERT INTO Country ([CountryName]) VALUES ('Niue (NZ)')
INSERT INTO Country ([CountryName]) VALUES ('Norfolk Island (Australia)')
INSERT INTO Country ([CountryName]) VALUES ('North Korea')
INSERT INTO Country ([CountryName]) VALUES ('Northern Mariana Islands (USA)')
INSERT INTO Country ([CountryName]) VALUES ('Norway')
INSERT INTO Country ([CountryName]) VALUES ('Oman')
INSERT INTO Country ([CountryName]) VALUES ('Pakistan')
INSERT INTO Country ([CountryName]) VALUES ('Palau')
INSERT INTO Country ([CountryName]) VALUES ('Palestine')
INSERT INTO Country ([CountryName]) VALUES ('Panama')
INSERT INTO Country ([CountryName]) VALUES ('Papua New Guinea')
INSERT INTO Country ([CountryName]) VALUES ('Paraguay')
INSERT INTO Country ([CountryName]) VALUES ('Peru')
INSERT INTO Country ([CountryName]) VALUES ('Philippines')
INSERT INTO Country ([CountryName]) VALUES ('Pitcairn Islands (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Poland')
INSERT INTO Country ([CountryName]) VALUES ('Portugal')
INSERT INTO Country ([CountryName]) VALUES ('Puerto Rico')
INSERT INTO Country ([CountryName]) VALUES ('Qatar')
INSERT INTO Country ([CountryName]) VALUES ('Republic of the Congo')
INSERT INTO Country ([CountryName]) VALUES ('Reunion (France)')
INSERT INTO Country ([CountryName]) VALUES ('Romania')
INSERT INTO Country ([CountryName]) VALUES ('Russia')
INSERT INTO Country ([CountryName]) VALUES ('Rwanda')
INSERT INTO Country ([CountryName]) VALUES ('Saint Barthelemy (France)')
INSERT INTO Country ([CountryName]) VALUES ('Saint Helena, Ascension and Tristan da Cunha (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Saint Kitts and Nevis')
INSERT INTO Country ([CountryName]) VALUES ('Saint Lucia')
INSERT INTO Country ([CountryName]) VALUES ('Saint Martin (France)')
INSERT INTO Country ([CountryName]) VALUES ('Saint Pierre and Miquelon (France)')
INSERT INTO Country ([CountryName]) VALUES ('Saint Vincent and the Grenadines')
INSERT INTO Country ([CountryName]) VALUES ('Samoa')
INSERT INTO Country ([CountryName]) VALUES ('San Marino')
INSERT INTO Country ([CountryName]) VALUES ('Sao Tom and Principe')
INSERT INTO Country ([CountryName]) VALUES ('Saudi Arabia')
INSERT INTO Country ([CountryName]) VALUES ('Senegal')
INSERT INTO Country ([CountryName]) VALUES ('Serbia')
INSERT INTO Country ([CountryName]) VALUES ('Seychelles')
INSERT INTO Country ([CountryName]) VALUES ('Sierra Leone')
INSERT INTO Country ([CountryName]) VALUES ('Singapore')
INSERT INTO Country ([CountryName]) VALUES ('Sint Maarten (Netherlands)')
INSERT INTO Country ([CountryName]) VALUES ('Slovakia')
INSERT INTO Country ([CountryName]) VALUES ('Slovenia')
INSERT INTO Country ([CountryName]) VALUES ('Solomon Islands')
INSERT INTO Country ([CountryName]) VALUES ('Somalia')
INSERT INTO Country ([CountryName]) VALUES ('South Africa')
INSERT INTO Country ([CountryName]) VALUES ('South Korea')
INSERT INTO Country ([CountryName]) VALUES ('South Sudan')
INSERT INTO Country ([CountryName]) VALUES ('Spain')
INSERT INTO Country ([CountryName]) VALUES ('Sri Lanka')
INSERT INTO Country ([CountryName]) VALUES ('Sudan')
INSERT INTO Country ([CountryName]) VALUES ('Suriname')
INSERT INTO Country ([CountryName]) VALUES ('Svalbard and Jan Mayen (Norway)')
INSERT INTO Country ([CountryName]) VALUES ('Swaziland')
INSERT INTO Country ([CountryName]) VALUES ('Sweden')
INSERT INTO Country ([CountryName]) VALUES ('Switzerland')
INSERT INTO Country ([CountryName]) VALUES ('Syria')
INSERT INTO Country ([CountryName]) VALUES ('Taiwan')
INSERT INTO Country ([CountryName]) VALUES ('Tajikistan')
INSERT INTO Country ([CountryName]) VALUES ('Tanzania')
INSERT INTO Country ([CountryName]) VALUES ('Thailand')
INSERT INTO Country ([CountryName]) VALUES ('Timor-Leste')
INSERT INTO Country ([CountryName]) VALUES ('Togo')
INSERT INTO Country ([CountryName]) VALUES ('Tokelau (NZ)')
INSERT INTO Country ([CountryName]) VALUES ('Tonga')
INSERT INTO Country ([CountryName]) VALUES ('Trinidad and Tobago')
INSERT INTO Country ([CountryName]) VALUES ('Tunisia')
INSERT INTO Country ([CountryName]) VALUES ('Turkey')
INSERT INTO Country ([CountryName]) VALUES ('Turkmenistan')
INSERT INTO Country ([CountryName]) VALUES ('Turks and Caicos Islands (UK)')
INSERT INTO Country ([CountryName]) VALUES ('Tuvalu')
INSERT INTO Country ([CountryName]) VALUES ('Uganda')
INSERT INTO Country ([CountryName]) VALUES ('Ukraine')
INSERT INTO Country ([CountryName]) VALUES ('United Arab Emirates')
INSERT INTO Country ([CountryName]) VALUES ('United Kingdom')
INSERT INTO Country ([CountryName]) VALUES ('United States Virgin Islands (USA)')
INSERT INTO Country ([CountryName]) VALUES ('Uruguay')
INSERT INTO Country ([CountryName]) VALUES ('Uzbekistan')
INSERT INTO Country ([CountryName]) VALUES ('Vanuatu')
INSERT INTO Country ([CountryName]) VALUES ('Vatican City')
INSERT INTO Country ([CountryName]) VALUES ('Venezuela')
INSERT INTO Country ([CountryName]) VALUES ('Vietnam')
INSERT INTO Country ([CountryName]) VALUES ('Wallis and Futuna (France)')
INSERT INTO Country ([CountryName]) VALUES ('Western Sahara')
INSERT INTO Country ([CountryName]) VALUES ('Yemen')
INSERT INTO Country ([CountryName]) VALUES ('Zambia')
INSERT INTO Country ([CountryName]) VALUES ('Zimbabwe')
GO

TRUNCATE TABLE [State]
GO
DECLARE @CountryId INT
SELECT @CountryId = [CountryId] FROM Country where [CountryName] = 'India'
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Andra Pradesh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Arunachal Pradesh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Assam')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Bihar')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Chhattisgarh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Goa')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Gujarat')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Haryana')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Himachal Pradesh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Jammu and Kashmir')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Jharkhand')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Karnataka')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Kerala')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Madya Pradesh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Maharashtra')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Manipur')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Meghalaya')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Mizoram')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Nagaland')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Orissa')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Punjab')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Rajasthan')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Sikkim')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Tamil Nadu')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Telagana')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Tripura')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Uttar Pradesh')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Uttaranchal')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'West Bengal')
GO
DECLARE @CountryId INT
SELECT @CountryId = [CountryId] FROM Country where [CountryName] = 'United States'
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Alabama')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Alaska')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Arizona')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Arkansas')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'California')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Colorado')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Connecticut')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Delaware')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Florida')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Georgia')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Hawaii')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Idaho')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Illinois')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Indiana')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Iowa')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Kansas')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Kentucky[upper-alpha 3]')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Louisiana')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Maine')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Maryland')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Massachusetts[upper-alpha 3]')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Michigan')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Minnesota')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Mississippi')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Missouri')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Montana')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Nebraska')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Nevada')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'New Hampshire')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'New Jersey')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'New Mexico')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'New York')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'North Carolina')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'North Dakota')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Ohio')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Oklahoma')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Oregon')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Pennsylvania[upper-alpha 3]')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Rhode Island[upper-alpha 4]')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'South Carolina')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'South Dakota')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Tennessee')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Texas')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Utah')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Vermont')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Virginia[upper-alpha 3]')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Washington')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'West Virginia')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Wisconsin')
INSERT INTO [State] ([CountryId], [StateName]) VALUES (@CountryId, 'Wyoming')
GO