
USE PMSNexus_Appraisal
GO
TRUNCATE TABLE [dbo].[AppConstantType]
GO

INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Type',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Duration',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Range',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Appraisal Status',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Operator',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('feedbackTag',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Notification Category',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('UI Type',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstantType] (APP_CONSTANT_TYPE_DESC,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE) VALUES ('Smiley',1,GETDATE(),1,GETDATE())
GO

