
USE PMSNexus_Appraisal
GO
TRUNCATE TABLE [dbo].[AppConstants]
GO
declare @AppConstantTypeId int
select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Type';

INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Percentage',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Range',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Number Count',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Duration';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Monthly',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Quarterly',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Half Yearly',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Yearly',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Appraisal Status';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self Appraisal Not Started',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self Appraisal In Progress',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self Appraisal Completed',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Appraiser Review In Progress',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Appraiser Review Completed',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self Appraisal Review Sent Back',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Management Review Completed',1,GETDATE(),1,GETDATE())


select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Operator';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'>',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'<',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'=',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'>=',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'<=',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'<= && >=',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='feedbackTag';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Awards',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Milestone',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Appreciations',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Feedback',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Escalation',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'General',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Notification Category';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Milestones',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Conversation',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='UI Type';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Slider',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'LOV',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Counter',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Smiley',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Timer',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Smiley';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Need Improvement',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Good',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Excellent',1,GETDATE(),1,GETDATE())


select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Appraisal Status';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Approved',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Rejected',1,GETDATE(),1,GETDATE())



select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Appraisal Status';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self-Appraisal in Progress-Feedback',1,GETDATE(),1,GETDATE())
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Self-Appraisal Completed-Feedback',1,GETDATE(),1,GETDATE())

select @AppConstantTypeId=APP_CONSTANT_TYPE_ID from [dbo].[AppConstantType] where APP_CONSTANT_TYPE_DESC='Smiley';
INSERT INTO [dbo].[AppConstants] (APP_CONSTANT_TYPE_ID,APP_CONSTANT_TYPE_VALUE,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE)
VALUES (@AppConstantTypeId,'Average',1,GETDATE(),1,GETDATE())
GO


