IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ProbationStatus')
CREATE TABLE [dbo].[ProbationStatus](
	[ProbationStatusId] [int] IDENTITY(1,1) NOT NULL,
	[ProbationStatusName] [varchar](250) NULL,
	[CreatedBy] [int] NULL,
	[CreatedOn] [datetime] NULL,
 CONSTRAINT [PK_ProbationStatus] PRIMARY KEY CLUSTERED 
(
	[ProbationStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO