IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EmployeesPersonalInfo')
	CREATE TABLE [dbo].[EmployeesPersonalInfo](
		[PersonalInfoId] [int] IDENTITY(1,1) NOT NULL,
		[EmployeeId] [int] NULL,
		[HighestQualification] [varchar] (2000) NULL,		
		[OtherEmail] [varchar](2000) NULL,
		[PersonalMobileNumber] [varchar](20) NULL,
		[BloodGroup]  [int] NULL,
		[FathersName] [varchar](250) NULL,
		[SpouseName] [varchar](250) NULL,
		[PermanentAddressLine1] [varchar](2000) NULL,
		[PermanentAddressLine2] [varchar](2000) NULL,
		[PermanentCity] [varchar](2000) NULL,
		[PermanentState] [int] NULL,
		[PermanentCountry] [int] NULL,
		[PermanentAddressZip] [varchar](2000) NULL,
		[CommunicationAddressLine1] [varchar](2000) NULL,
		[CommunicationAddressLine2] [varchar](2000) NULL,
		[CommunicationCity] [varchar](2000) NULL,
		[CommunicationState] [int] NULL,
		[CommunicationCountry] [int] NULL,
		[CommunicationAddressZip] [varchar](2000) NULL,
		[Nationality] [varchar](250) NULL,
		[PANNumber] [varchar](2000) NULL,
		[UANNumber] [varchar](2000) NULL,
		[DrivingLicense] [varchar](2000) NULL,
		[AadhaarCardNumber] [varchar](2000) NULL,
		[PassportNumber] [varchar](2000) NULL,
		[EmergencyContactName] [varchar](2000) NULL,
		[EmergencyContactRelation] [varchar](100) NULL,
	    [EmergencyMobileNumber] [varchar](20) NULL,
		[ReferenceContactName] [varchar](2000) NULL,
		[ReferenceEmailId] [varchar](100) NULL,
	    [ReferenceMobileNumber] [varchar](20) NULL,
	    [IsJoiningBonus] [bit] NULL,
		[JoiningBonusAmmount] [DECIMAL](18,2) NULL,
		[JoiningBonusCondition] [varchar] (max) NULL,
		[AccountHolderName] [varchar] (max) NULL,
		[BankName] [varchar] (max) NULL,
		[IFSCCode] [varchar](50) NULL,
		[AccountNumber] [DECIMAL](20,2)  NULL,
		[CreatedOn] [datetime] NULL,
		[ModifiedOn] [datetime] NULL,
		[CreatedBy] [int] NULL,
		[ModifiedBy] [int] NULL,		
	PRIMARY KEY CLUSTERED 
	(
		[PersonalInfoId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
GO
