USE [PMSNexus_Projects]
GO

TRUNCATE TABLE CurrencyType
GO

INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('India', 'INR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('United States', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('European Union', 'EUR', GETDATE(), 1)
GO
/*INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Afghanistan', 'AFN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Albania', 'ALL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Algeria', 'DZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('American Samoa', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Andorra', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Angola', 'AOA', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Anguilla', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Antigua and Barbuda', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Argentina', 'ARS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Armenia', 'AMD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Aruba', 'AWG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Australia', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Austria', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Azerbaijan', 'AZN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bahamas', 'BSD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bahrain', 'BHD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Banglades', 'BDT', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Barbados', 'BBD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Belarus', 'BYN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Belgium', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Belize', 'BZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Benin', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bermuda', 'BMD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bhutan', 'BTN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bolivia', 'BOB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bosnia-Herzegovina', 'BAM', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Botswana', 'BWP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bouvet Island', 'NOK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Brazil', 'BRL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('British Indian O. Terr.', 'GBP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('British Virgin Islands', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Brunei Darussalam', 'BND', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Bulgaria', 'BGN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Burkina Faso', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Burundi', 'BIF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cambodia', 'KHR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cameroon', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Canada', 'CAD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cape Verde', 'CVE', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cayman Islands', 'KYD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Central African Rep.', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Chad', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Chile', 'CLP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('China', 'CNY', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Christmas Island', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cocos (Keeling) Islands', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Colombia', 'COP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Comoros', 'KMF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Congo (Brazzaville)', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cook Islands', 'NZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Costa Rica', 'CRC', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Croatia', 'HRK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cuba', 'CUC', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Cyprus', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Czech Republic', 'CZK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Democratic Republic of Congo (Kinshasa-Zaire)', 'CDF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Denmark', 'DKK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Djibouti', 'DJF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Dominica', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Dominican Republic', 'DOP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ecuador', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Egypt', 'EGP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('El Salvador', 'SVC', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Eritrea', 'ERN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Estonia', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ethiopia', 'ETB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Falkland Isl., Malvinas', 'FKP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Faroe Islands', 'DKK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Fiji', 'FJD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Finland', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('France', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('France, Metropolitan', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('French Guiana', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('French Polynesia', 'XPF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('French Southern Terr.', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Gabon', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Gambia', 'GMD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Georgia', 'GEL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Germany', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ghana', 'GHS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Gibraltar', 'GIP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Great Britain - UK', 'GBP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Greece', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Greenland (Denmark)', 'DKK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Grenada', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guadaloupe', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guam (US)', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guatemala', 'GTQ', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guernsey', 'GGP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guinea (Conakry)', 'GNF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guinea Bissau', 'XAF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Guyana', 'GYD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Haiti', 'HTG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Heard and McDonald Isl.', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Honduras', 'HNL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Hong Kong', 'HKD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Hungary', 'HUF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Iceland', 'ISK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Indonesia', 'IDR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Iran', 'IRR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Iraq', 'IQD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ireland', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Isle of Man', 'IMP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Israel', 'ILS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Italy', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ivory Coast', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Jamaica', 'JMD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Japan', 'JPY', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Jersey', 'JEP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Jordan', 'JOD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Kazakhstan', 'KZT', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Kenya', 'KES', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Kiribati', 'KID', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Kuwait', 'KWD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Kyrgyz Republic', 'KGS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Laos', 'LAK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Latvia', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Lebanon', 'LBP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Lesotho', 'LSL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Liberia', 'LRD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Libya', 'LYD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Liechtenstein', 'CHF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Lithuania', 'LTL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Luxembourg', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Macau', 'MOP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Macedonia', 'MKD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Madagascar', 'MGA', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Malawi', 'MWK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Malaysia', 'MYR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Maldives', 'MVR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mali', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Malta', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Marshall Islands', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Martinique', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mauritania', 'MRU', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mauritius', 'MUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mayotte', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mexico', 'MXN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Micronesia', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Moldova', 'MDL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Monaco', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mongolia', 'MNT', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Montenegro', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Montserrat', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Morocco', 'MAD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Mozambique', 'MZN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Myanmar', 'MMK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Namibia', 'NAD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Nauru', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Nepal', 'NPR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Netherland Antilles', 'ANG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Netherlands', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('New Caledonia', 'XPF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('New Zealand', 'NZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Nicaragua', 'NIO', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Niger', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Nigeria', 'NGN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Niue', 'NZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Norfolk Island', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('North Korea', 'KPW', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Northern Mariana Isl.', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Norway', 'NOK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Oman', 'OMR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Pakistan', 'PKR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Palau', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Palestine', 'ILS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Panama', 'PAB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Papua New Guinea', 'PGK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Paraguay', 'PYG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Peru', 'PEN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Philippines', 'PHP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Pitcairn', 'NZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Poland', 'PLN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Portugal', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Puerto Rico', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Qatar', 'QAR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Reunion', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Romania', 'RON', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Russian Federation', 'RUB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Rwanda', 'RWF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Saint Lucia', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Saint Pierre and Miquelon', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('San Marino', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Saudi Arabia', 'SAR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Senegal', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Serbia', 'RSD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Seychelles', 'SCR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Sierra Leone', 'SLL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Singapore', 'SGD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Sint Maarten (Dutch part)', 'ANG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Slovakia', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Slovenia', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Solomon Islands', 'SBD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Somalia', 'SOS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('South Africa', 'ZAR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('South Georgia and South Sandwich Islands', 'GBP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('South Korea', 'KRW', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('South Sudan', 'SSP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Soviet Union', 'RUB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Spain', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Sri Lanka', 'LKR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('St. Helena', 'SHP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('St. Tome and Principe', 'STN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('St.Kitts Nevis Anguilla', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('St.Vincent and Grenadines', 'XCD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Sudan', 'SDG', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Suriname', 'SRD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Svalbard and Jan Mayen Is', 'NOK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Swaziland', 'SZL', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Sweden', 'SEK', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Switzerland', 'CHF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Syria', 'SYP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Taiwan', 'TWD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tajikistan', 'TJS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tanzania', 'TZS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Thailand', 'THB', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Timor-Leste', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Togo', 'XOF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tokelau', 'NZD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tonga', 'TOP', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Trinidad and Tobago', 'TTD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tunisia', 'TND', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Turkey', 'TRY', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Turkmenistan', 'TMT', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Turks and Caicos Islands', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Tuvalu', 'AUD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Uganda', 'UGX', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Ukraine', 'UAH', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('United Arab Emirates', 'AED', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Uruguay', 'UYU', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('US Minor outlying Isl.', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('US Virgin Islands', 'USD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Uzbekistan', 'UZS', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Vanuatu', 'VUV', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Vatican City State', 'EUR', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Venezuela', 'VES', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Vietnam', 'VND', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Wallis and Futuna Islands', 'XPF', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Western Sahara', 'MAD', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Western Samoa', 'WST', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Yemen', 'YER', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Yugoslavia', 'YUN', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Zambia', 'ZMW', GETDATE(), 1)
INSERT INTO CurrencyType(Country, CurrencyCode, CreatedOn, CreatedBy) VALUES('Zimbabwe', 'ZWL', GETDATE(), 1)*/
GO

TRUNCATE TABLE ProjectType
GO

INSERT INTO ProjectType(ProjectTypeDescription, CreatedOn, CreatedBy) VALUES('Fixed bid', GETDATE(), 1)
INSERT INTO ProjectType(ProjectTypeDescription, CreatedOn, CreatedBy) VALUES('Time and material', GETDATE(), 1)
INSERT INTO ProjectType(ProjectTypeDescription, CreatedOn, CreatedBy) VALUES('Non Billable', GETDATE(), 1)
GO

