USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ConversationTags')
CREATE TABLE ConversationTags (
  TAG_ID int identity(1,1) NOT NULL,
  TAG_DESCRIPTION nvarchar(100) NULL,
  TAG_BACKGROUND_COLOR nvarchar(45) NULL,
  TAG_ICON_URL nvarchar(500) NULL,
  CREATED_BY int NULL,
  CREATED_DATE datetime NULL,
  UPDATED_BY int NULL,
  UPDATED_DATE datetime NULL,
  PRIMARY KEY (TAG_ID)
)