USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AppConstants')
	CREATE TABLE AppConstants (
  APP_CONSTANT_ID int identity(1,1),
  APP_CONSTANT_TYPE_ID int NOT NULL,
  APP_CONSTANT_TYPE_VALUE nvarchar(1000) NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (APP_CONSTANT_ID)
  )
GO