USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ContinuousFeedBack')
	CREATE TABLE ContinuousFeedBack (
  COMMENT_ID int identity(1,1) NOT NULL,
  APP_CYCLE_ID int NOT NULL,
  EMPLOYEE_ID int NOT NULL,
  CONVO_TOPIC varchar(1000) NOT NULL,
  CONVO_TAG_ID int NOT NULL,
  COMMENT varchar(3000)  NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  CONVO_TOPIC_ID int NULL,
  PRIMARY KEY (COMMENT_ID)
)
GO