USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EmployeeAppraisalMaster')

CREATE TABLE EmployeeAppraisalMaster (
  APP_CYCLE_ID int NOT NULL,
  EMPLOYEE_ID int NOT NULL,
  ENTITY_ID int NOT NULL,
  EMPLOYEE_ROLE_ID int NOT NULL,
  EMPLOYEE_DEPT_ID int NOT NULL,
  EMPLOYEE_MANAGER_ID int NOT NULL,
  EMPLOYEE_SELF_RATING decimal(18,2) NULL,
  EMPLOYEE_APPRAISER_RATING decimal(18,2) NULL,
  EMPLOYEE_FINAL_RATING decimal(18,2) NULL,   
  APPRAISAL_STATUS int NULL,
  IsBUHeadRevert bit NULL DEFAULT (0) WITH VALUES,
  IsRevertRating bit NULL DEFAULT (0) WITH VALUES,
  IsBUHeadApproved bit NULL DEFAULT (0) WITH VALUES,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (APP_CYCLE_ID,EMPLOYEE_ID)
  )
GO
