USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AppConstantType')
CREATE TABLE AppConstantType (
  APP_CONSTANT_TYPE_ID int identity(1,1) NOT NULL,
  APP_CONSTANT_TYPE_DESC nvarchar(500) NOT NULL,
  CREATED_BY int NULL,
  CREATED_DATE datetime NULL,
  UPDATED_BY int NULL,
  UPDATED_DATE datetime NULL,
  PRIMARY KEY (APP_CONSTANT_TYPE_ID)
) 