USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ObjectiveMaster')

CREATE TABLE ObjectiveMaster (
  OBJECTIVE_ID int identity(1,1) NOT NULL,
  OBJECTIVE_NAME nvarchar(500) NOT NULL,
  OBJECTIVE_SHORT_NAME nvarchar(100) NULL,
  OBJECTIVE_DESCRIPTION nvarchar(2000) NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  OBJECTIVE_IMAGE_URL nvarchar(500)  NULL,
  PRIMARY KEY (OBJECTIVE_ID)
) 
GO
