USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='EntityMaster')

CREATE TABLE EntityMaster (
  ENTITY_ID int identity(1,1) NOT NULL,
  ENTITY_NAME nvarchar(500) NOT NULL,
  ENTITY_SHORT_NAME nvarchar(100) NULL,
  ENTITY_DESCRIPTION nvarchar(2000) NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (ENTITY_ID)
) 
GO
