USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='KeyResultMaster')

CREATE TABLE KeyResultMaster (
  KEY_RESULT_ID int identity(1,1) NOT NULL,
  KEY_RESULT_NAME nvarchar(500) NOT NULL,
  KEY_RESULT_SHORT_NAME nvarchar(100) NULL,
  KEY_RESULT_DESCRIPTION nvarchar(2000) NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (KEY_RESULT_ID)
) 
GO
