USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='SDSTokenDTLS')

CREATE TABLE SDSTokenDTLS (
  STD_TOKEN_ID int identity(1,1) NOT NULL,
  STD_CLIENT_IP nvarchar(255)  NULL,
  SCD_CREATED_BY int  NULL,
  SCD_CREATED_DATE datetime  NULL,
  STD_DEVICE_TYPE nvarchar(255)  NULL,
  STD_IS_REMEMBER int  NULL,
  STD_TOKEN nvarchar(255)  NULL,
  STD_TOKEN_EXPIRY_TIME datetime  NULL,
  SCD_UPDATED_BY int  NULL,
  SCD_UPDATED_DATE datetime  NULL,
  STD_USER_ID int  NULL,
  PRIMARY KEY (STD_TOKEN_ID)
) 
GO
