USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersionBenchMarks')


CREATE TABLE VersionBenchMarks (
  BENCHMARK_ID int identity(1,1) NOT NULL,
  VERSION_ID int NOT NULL,
  DEPT_ID int NOT NULL,
  ROLE_ID int NOT NULL,
  OBJECTIVE_ID int NOT NULL,
  KEY_RESULT_ID int NOT NULL,
  RANGE_FROM decimal(18,2) NULL,
  RANGE_TO decimal(18,2) NULL,
  BENCHMARK_VALUE decimal(18,2) NULL,
  BENCHMARK_WEIGHTAGE decimal(18,2) NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  BENCHMARK_SUBJECTIVE_NAME nvarchar(45) NULL,
  PRIMARY KEY (BENCHMARK_ID)
  )
GO
