USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersionKeyResultsGroup')

CREATE TABLE VersionKeyResultsGroup (
  KEY_RESULTS_GROUP_ID int identity(1,1) NOT NULL,
  VERSION_ID int NOT NULL,
  DEPT_ID int NOT NULL,
  ROLE_ID int NOT NULL,
  OBJECTIVE_ID int NOT NULL,
  KEY_RESULTS_GROUP_NAME nvarchar(500) NOT NULL,
  MANDATORY_KEY_RESULT_OPTIONS int NOT NULL,
  KEY_RESULT_GROUP_WEIGHTAGE decimal(18,2) NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (KEY_RESULTS_GROUP_ID)
  )
GO
