USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersionKeyResultsGroupDetails')

CREATE TABLE VersionKeyResultsGroupDetails (
  VERSION_ID int NOT NULL,
  DEPT_ID int NOT NULL,
  ROLE_ID int NOT NULL,
  OBJECTIVE_ID int NOT NULL,
  KEY_RESULTS_GROUP_ID int NOT NULL,
  KEY_RESULT_ID int NOT NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (VERSION_ID,DEPT_ID,ROLE_ID,OBJECTIVE_ID,KEY_RESULTS_GROUP_ID,KEY_RESULT_ID)
  )
GO
