USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersionMaster')

CREATE TABLE VersionMaster (
  VERSION_ID int identity(1,1) NOT NULL,
  VERSION_NAME nvarchar(500) NOT NULL,
  VERSION_DESC nvarchar(2000)  NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  VERSION_CODE Nvarchar(100),
  PRIMARY KEY (VERSION_ID)
) 
GO
