USE [PMSNexus_Appraisal]
Go
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersionDepartmentRoleObjective')

CREATE TABLE VersionDepartmentRoleObjective (
  VERSION_ID int NOT NULL,
  DEPT_ID int NOT NULL,
  ROLE_ID int NOT NULL,
  OBJECTIVE_ID int NOT NULL,
  OBJECTIVE_WEIGHTAGE decimal(18,2) NULL,
  CREATED_BY int  NULL,
  CREATED_DATE datetime  NULL,
  UPDATED_BY int  NULL,
  UPDATED_DATE datetime  NULL,
  PRIMARY KEY (VERSION_ID,DEPT_ID,ROLE_ID,OBJECTIVE_ID)
  )
GO
